env:
  - FLASK_APP="app/main_flask.py"
language: python
python:
  - "3.7"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest